#!/usr/bin/env bash
#
# Script description.
#
# Author: First Last <first.last@wandisco.com>

set -euo pipefail
IFS=$'\n'

readonly APP_VER="1.0"
readonly APP_NAME="$(basename "$0")"
readonly APP_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly APP_LIB="${APP_DIR}/functions.sh"
readonly APP_TMP="$(mktemp -dt "${APP_NAME}.XXXXXXXX")"

if [[ -r "${APP_LIB}" ]]; then
  . "${APP_LIB}"
else
  printf "Unable to load library file %s, exiting.\n" \
    "$(basename "${APP_LIB}")" >&2
  exit 1
fi

display_help() {
  display_version
  cat <<HELP
Usage: ${APP_NAME} [OPTIONS]
AVAILABLE OPTIONS:
-h  Print this help summary page
-v  Print version number
HELP
}

get_opts() {
  while getopts ":vh" opt; do
    case $opt in
      v)
        display_version
        die 0
        ;;
      h)
        display_help
        die 0
        ;;
      :)
        die 1 "Option -${OPTARG} requires an argument"
        ;;
      *)
        die 1 "Invalid option -${OPTARG}"
        ;;
    esac
  done
}

main() {
  trap cleanup EXIT SIGHUP SIGINT SIGTERM

  get_opts "$@"
  echo "Hello World!"
  die 0
}

main "$@"
