#!/usr/bin/env bash
#
# Script description.
#
# Author: First Last <first.last@wandisco.com>

set -euo pipefail

readonly APP_VER="1.0"
readonly APP_NAME="$(basename "$0")"
readonly APP_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly APP_TMP="$(mktemp -dt "${APP_NAME}.XXXXXXXX")"

die() {
  local msg="${1:-}"
  local -i code=${2:-1}

  if [[ -n "$msg" ]]; then
    printf "%s\n" "$msg" >&2
  fi
  exit $code
}

display_version() {
  printf "%s version %s\n" "$APP_NAME" "$APP_VER"
}

cleanup() {
  [[ -d "$APP_TMP" ]] && rm -rf "$APP_TMP"
}

display_help() {
  display_version
  cat <<HELP
Usage: ${APP_NAME} [OPTIONS]
AVAILABLE OPTIONS:
-h  Print this help summary page
-v  Print version number
HELP
}

get_opts() {
  while getopts ":vh" opt; do
    case $opt in
      v)
        display_version
        exit 0
        ;;
      h)
        display_help
        exit 0
        ;;
      :)
        die "Option -${OPTARG} requires an argument"
        ;;
      *)
        die "Invalid option -${OPTARG}"
        ;;
    esac
  done
}

main() {
  trap cleanup EXIT SIGHUP SIGINT SIGTERM

  get_opts "$@"
  printf "Hello World!\n"
  exit 0
}

main "$@"
